# -*- MakeFile -*-

# MACRO = substitute with this

# directories

TMP_DIR = $(LIBALX_DIR)/tmp/


# target: dependencies
#	action

all:
	$(Q)cd $(TMP_DIR) && $(MAKE) && cd ..


clean:
	$(Q)cd $(TMP_DIR) && $(MAKE) clean && cd ..
	@echo  "Clean libalx"
